Galerie page
WildCodeSchool/lille-0920b-js-mentali-iss pull request #10
Opened 2020-11-13 12:54 UTC by Marie-Garde

2020-11-13 14:27 UTC, Guy-deMessimy approved these changes

2020-11-13 14:27 UTC, Guy-deMessimy approved these changes, later dismissed
ok

2020-11-13 14:42 UTC, LoicBrassart requested changes
Some Evils, please revise

2020-11-13 14:42 UTC, LoicBrassart commented on package.json
> +    "i": "^0.3.6",
... `i` ? What's this package ?

2020-11-13 14:42 UTC, LoicBrassart commented on src/components/ChooseADate.jsx
> +                  <option value="31">31</option>
I heard about a `for` instruction, very useful for this kind of thing... :smirk:

2020-11-13 14:42 UTC, LoicBrassart commented on src/components/ChooseADate.jsx
> +                  <option value="1996">1996</option>
Same here, a `for` would have been enough !

2020-11-13 14:42 UTC, LoicBrassart commented on src/components/GaleriePage.jsx
> +        <ChooseADate /> //*On appelle le composant pour la 2eme partie
This is not a comment !

2020-11-15 21:04 UTC, Guy-deMessimy approved these changes, later dismissed

2020-11-16 08:07 UTC, LoicBrassart requested changes
Evil cook spotted !

2020-11-16 08:07 UTC, LoicBrassart commented on package.json
>  {
Note: this file was re-indented. It has changed globally, I don't know if something was added :shrug:

2020-11-16 08:07 UTC, LoicBrassart commented on src/components/ChooseADate.jsx
>    constructor(props) {
Generally speaking, one leaves the `constructor` method at the top of the file (since it is the first method called)

2020-11-16 08:07 UTC, LoicBrassart commented on src/components/ChooseADate.jsx
> +                  <option value="yaer">Year</option>
"yaer" ?

2020-11-16 08:07 UTC, LoicBrassart commented on src/components/ChooseADate.jsx
> +              <ChooseADateImg src="/photos/choseadate.png" alt="cook" />
Well tried ;-)

2020-11-16 08:08 UTC, Guy-deMessimy commented on src/components/ChooseADate.jsx
> +                  <option value="yaer">Year</option>
ok yeah

2020-11-16 10:08 UTC, Guy-deMessimy approved these changes

2020-11-16 12:01 UTC, LoicBrassart approved these changes
Much better ;-)

2020-11-16 16:09 UTC, merged