Front page
WildCodeSchool/lille-0920b-js-mentali-iss pull request #11
Opened 2020-11-13 14:24 UTC by Guy-deMessimy

2020-11-13 14:31 UTC, Marie-Garde submitted a review, later dismissed
Splendide !

2020-11-13 14:46 UTC, LoicBrassart requested changes
Some Evils, please revise

2020-11-13 14:46 UTC, LoicBrassart commented on package.json
> +    "i": "^0.3.6",
`i` again ?

2020-11-13 14:46 UTC, LoicBrassart commented on src/components/Sidebar.jsx
> +  console.log(this.state.isOpen)
Nope !

2020-11-13 14:46 UTC, LoicBrassart commented on src/index.js
> +
This new empty line is useless

2020-11-16 10:00 UTC, Marie-Garde approved these changes, later dismissed
Nice !

2020-11-16 12:02 UTC, LoicBrassart commented
I could review right now, but I'd have to do it again after conflicts are solved...
Could you please fix it and reassign me afterwards ?

2020-11-17 16:41 UTC, Marie-Garde submitted a review, later dismissed
Ok

2020-11-18 15:16 UTC, LoicBrassart requested changes
Some minor evils

2020-11-18 15:16 UTC, LoicBrassart commented on src/components/Footer.jsx
> +const H4TER = styled.h4`
I still don't like this tag name, even though you explained it to me

2020-11-18 15:16 UTC, LoicBrassart commented on src/components/Footer.jsx
> +const SocialLi = styled.li`
Ah ? A new Eveelution ? A very nice one ? =)

2020-11-18 15:16 UTC, LoicBrassart commented on src/components/Sidebar.jsx
> +     isMenuOpen () {
This function name makes me think "Is my Menu open ?", not "I want to toggle my menu"
You should rename this "toggleMenu", it'd be clearer

2020-11-19 09:29 UTC, Marie-Garde approved these changes
Nickel !

2020-11-20 08:52 UTC, LoicBrassart approved these changes
No more Evil ! :clap:

2020-11-23 07:35 UTC, merged